### ISSUE TITLE
[Epic] Flashcard

### ISSUE THREAD

**Issue by ShyraiDan** [ShyraiDan/LynadLearn#6]
- [x] We need to start placing list cards from the left side of the page 
![{22B46BB2-0BCB-4CD3-B5E2-F0A00B953AEA}](https://github.com/user-attachments/assets/0648da40-36b1-4c44-8f7e-3401560d193c)
- [x] Add theme for title when we don't have words in the list
![{A00ACAEA-FFE2-4B0B-BBF4-DB3E8021097A}](https://github.com/user-attachments/assets/e2f104af-9898-426a-9dd8-3b8995bd2f2d)
- [x] User is not able to start the flashcard session with words like 
![{BB71EABD-A2F6-47FF-98F5-6200D28B054C}](https://github.com/user-attachments/assets/548f01cc-febd-4f7f-8e0e-1be746cb1d12)
- [x] Add dark theme for Congrats modal after finishing all flashcards
![{3A065788-2142-4EAD-9AD1-2B28161EB80A}](https://github.com/user-attachments/assets/f2598d82-c689-4018-a4bc-4c3642f931ee)
- [x] Fix appearing Congrats modal in flashcards (it appears not when the user finishes all the wrong cards)
- [x] Implement flashcards for default lists
- [x] Implement logic to add new words in Congrats modal (only for default lists, not custom ones)
- [x] User can see different messages during small period of time when they starts a new flashcard session
- [x] Implement existing shuffleArray function to words array
- [x] Think about closing Congrats modal (maybe it will be better to remove cross there and opportunity to close modal by pressing outside of it) (optional)
